<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DEV-NANO1" failures="1" tests="8" name="tests.VistaTestScenariosClass" time="68.023" errors="0" timestamp="2024-05-26T09:49:30 GST" skipped="0">
  <testcase classname="tests.VistaTestScenariosClass" name="LoginFunctionality_PositiveScenario_LoginScenario3" time="9.410">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at utils.UIAutomationUtils.TakeScreenshot(UIAutomationUtils.java:148)
at tests.VistaTestScenariosClass.LoginFunctionality_PositiveScenario_LoginScenario3(VistaTestScenariosClass.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LoginFunctionality_PositiveScenario_LoginScenario3 -->
  <system-out/>
  <testcase classname="tests.VistaTestScenariosClass" name="RegisterationFunctionality__NegativeScenaio_RegisterationScenario4" time="7.468"/>
  <system-out/>
  <testcase classname="tests.VistaTestScenariosClass" name="LoginFunctionality_PositiveScenario_LoginScenario1" time="7.360"/>
  <system-out/>
  <testcase classname="tests.VistaTestScenariosClass" name="RegisterationFunctionality__NegativeScenaio_RegisterationScenario2" time="8.995"/>
  <system-out/>
  <testcase classname="tests.VistaTestScenariosClass" name="RegisterationFunctionality__NegativeScenaio_RegisterationScenario5" time="8.222"/>
  <system-out/>
  <testcase classname="tests.VistaTestScenariosClass" name="RegisterationFunctionality__NegativeScenaio_RegisterationScenario3" time="9.156"/>
  <system-out/>
  <testcase classname="tests.VistaTestScenariosClass" name="LoginFunctionality_NegativeScenario_LoginScenario2" time="7.688"/>
  <system-out/>
  <testcase classname="tests.VistaTestScenariosClass" name="RegisterationFunctionality_PositiveScenario_RegisterationScenario1" time="9.724"/>
  <system-out/>
</testsuite> <!-- tests.VistaTestScenariosClass -->
